-  name: sample on varible
   hosts: all
   vars:
     URL: sample.vars.com
   tasks:
    - name: var from  plan
      debug:
        msg: URL ={{URL}}
    - name: var from task
      vars:
       URL: sample.vars.com
      debug:
        msg: URL= {{URL}}

-  name: vars from file
   hosts: all
   vars_files:
     - example.vars.yml
   tasks:
    - name: vars from file
      debug:
        msg: URL={{URL}}

- name: vars from invfile
  hosts: all
  tasks:
   - name: vars from  inv
     debug:
      msg: URL={{URL}}

- name: Demo on vars from roles
  hosts: all
  roles:
    - name: demo