- name: sample var declaration
  hosts: all
  vars:
    URL: sample.variable.com
  tasks:
      - name: print varibale from play
        debug:
          msg: URL = {{ URL }}

      - name: print varible from task
        vars:
          URL: sample.task.com
        debug:
          msg: URL= {{URL}}